### ISSUE TITLE
PocketNes compile error

### ISSUE THREAD

**Issue by superkahraman** [patters-syno/gba-emu-compilation-builders#2]
`python3 pocketnes_compile.py -h

  File "C:\Users\mess\Desktop\Emulation Playground\Builder\nes\pocketnes_compile.py", line 131
    compilation += cb"\0" * ((256 - ((len(compilation) + EMU_HEADER + NES_HEADER)%256))%256)
                     ^^^^
SyntaxError: invalid syntax`

I'm getting this error. 
How can I overcome this problem?

**Comment by patters-match** [comment]
Well spotted. That was a silly typo - `cb"\0"` should have been `b"\0"`. It was introduced with [this commit](https://github.com/patters-match/gba-emu-compilation-builders/commit/b3ae58f31dae3e2da1672a9194a8474fa12f7c40#diff-133355484d9eb5fda7bd85ebce95c5c5f4210a583fe77a1fc544b72966120a7f) when I went back over all the scripts folding in some improvements from the newer ones. I've fixed that now. Re-clone the repo for the fix.

**Comment by superkahraman** [comment]
I updated script and i get following error now.

`> python3 pocketnes_compile.py -h

  File "C:\Users\mess\Desktop\Emulation Playground\Builder\nes\pocketnes_compile.py", line 201
    raise Exception(f'unsupported filetype for compilation - {romfilename}')
    ^
IndentationError: expected an indented block after 'else' statement on line 200`

**Comment by patters-match** [comment]
My apologies. Please try again now.
